#!/usr/bin/env python3
"""asset_map.py — generate the project's script <-> asset dependency map (spec: dependency-map / TD-051).

Every fresh session used to re-scour the tree to answer "which script loads this PNG? which
generator writes it? who preloads this .gd?". This derives that graph by static analysis and writes
it to docs/technical/asset-map.md, so the next session greps one trustworthy file instead.

DERIVE, don't hand-maintain: a stale dependency doc is worse than none. `--check` makes staleness a
hard failure, so the committed map can never silently drift.

Edges captured (text regex, stdlib only):
  - GDScript  load("res://…") / preload("res://…")      -> script -> asset | script -> script
  - Scene     [ext_resource … path="res://…"]           -> scene  -> resource
  - Generator write_png("name.png", …) (also A.write_png) under client/assets/ui/  -> generator -> asset

Templated paths (`%d`,`%s`,`%0Nd`,`{}`) are globbed against on-disk files; anything unresolvable is
listed under "Unresolved dynamic references" (never silently dropped).

Usage:
  python3 tools/asset_map.py            # regenerate docs/technical/asset-map.md
  python3 tools/asset_map.py --check    # exit 1 if the committed map is stale (CI / session trust)
  python3 tools/asset_map.py --selftest # assert known edges + determinism; exit 1 on failure
"""
import argparse
import difflib
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLIENT = os.path.join(ROOT, "client")
OUT = os.path.join(ROOT, "docs", "technical", "asset-map.md")

RE_LOAD = re.compile(r'\b(load|preload)\(\s*"(res://[^"]+)"')
RE_EXT = re.compile(r'\[ext_resource\b[^\]]*?\bpath="(res://[^"]+)"')
RE_WRITE = re.compile(r'\b(?:A\.)?write_png\(\s*"([^"]+)"')
# A load/preload/ext string built from a variable (has no literal res:// we can ground). We still
# want to know it exists so the map can flag it. Matches a load( that is NOT a plain "res://…".
RE_DYN = re.compile(r'\b(?:load|preload)\(\s*(?!"res://)([^)]*?)\)')

BANNER = (
    "<!-- GENERATED by tools/asset_map.py — DO NOT EDIT BY HAND.\n"
    "     Regenerate:  python3 tools/asset_map.py     Verify current:  python3 tools/asset_map.py --check\n"
    "     The graph below is derived from source; edit the code, then regenerate. -->\n"
)


def _rel(path):
    return os.path.relpath(path, ROOT).replace(os.sep, "/")


def _res_to_fs(res_path):
    """res://foo -> <client>/foo (absolute)."""
    return os.path.join(CLIENT, res_path[len("res://"):])


def _template_to_glob(p):
    """Turn a Python format-string path into a glob; returns (glob_or_literal, is_pattern)."""
    g = re.sub(r"%0?\d*[disxX]", "*", p)
    g = re.sub(r"\{[^}]*\}", "*", g)
    return g, ("*" in g)


def _walk(exts, *roots):
    for r in roots:
        for dirpath, dirs, files in os.walk(r):
            dirs[:] = [d for d in dirs if d not in (".godot", "node_modules", ".import", ".captures")]
            for f in files:
                if os.path.splitext(f)[1] in exts:
                    yield os.path.join(dirpath, f)


def scan():
    """Return the dependency model as plain dicts/lists (all sets become sorted lists at emit)."""
    producers = {}      # asset rel -> set[generator rel]
    consumers = {}      # asset rel -> set[(consumer rel, kind)]
    loads = {}          # gd rel -> set[asset rel]
    preloads = {}       # gd rel -> set[gd rel]
    loaded_by = {}      # gd/tscn rel -> set[(consumer rel, kind)]
    writes = {}         # generator rel -> set[asset rel]
    dangling = set()    # (referenced res path, source rel, lineno)
    unresolved = []     # (source rel, lineno, raw)

    def add_consumer(asset_rel, consumer_rel, kind):
        consumers.setdefault(asset_rel, set()).add((consumer_rel, kind))

    def resolve_ref(res_path, src_rel, lineno, kind):
        """Ground a res:// reference to on-disk file(s); record edges or dangling."""
        fs = _res_to_fs(res_path)
        g, is_pattern = _template_to_glob(fs)
        hits = sorted(glob.glob(g)) if is_pattern else ([fs] if os.path.exists(fs) else [])
        if not hits:
            dangling.add((res_path, src_rel, lineno))
            return
        for hit in hits:
            hit_rel = _rel(hit)
            if hit_rel.endswith(".gd"):
                preloads.setdefault(src_rel, set()).add(hit_rel)
                loaded_by.setdefault(hit_rel, set()).add((src_rel, kind))
            else:
                loads.setdefault(src_rel, set()).add(hit_rel)
                add_consumer(hit_rel, src_rel, kind)
                loaded_by.setdefault(hit_rel, set()).add((src_rel, kind))

    # GDScript: load / preload
    for path in _walk({".gd"}, os.path.join(CLIENT, "scripts")):
        src_rel = _rel(path)
        for i, line in enumerate(open(path, encoding="utf-8", errors="replace"), 1):
            for kind, res in RE_LOAD.findall(line):
                resolve_ref(res, src_rel, i, kind)
            for m in RE_DYN.finditer(line):
                arg = m.group(1).strip()
                # a res:// pattern-string with a % is handled by RE_LOAD's literal capture already;
                # only flag args that carry NO res:// literal at all (path from a variable/concat).
                if "res://" not in arg:
                    unresolved.append((src_rel, i, ("load/preload " + arg)[:120]))

    # Scenes: ext_resource
    for path in _walk({".tscn"}, os.path.join(CLIENT, "scenes")):
        src_rel = _rel(path)
        for i, line in enumerate(open(path, encoding="utf-8", errors="replace"), 1):
            for res in RE_EXT.findall(line):
                resolve_ref(res, src_rel, i, "ext_resource")

    # Generators: write_png under client/assets/ui
    for path in _walk({".py"}, os.path.join(CLIENT, "assets")):
        src_rel = _rel(path)
        base_dir = os.path.dirname(path)  # generators write relative to their own dir (CWD convention)
        for i, line in enumerate(open(path, encoding="utf-8", errors="replace"), 1):
            for name in RE_WRITE.findall(line):
                fs = os.path.join(base_dir, name)
                g, is_pattern = _template_to_glob(fs)
                hits = sorted(glob.glob(g)) if is_pattern else ([fs] if os.path.exists(fs) else [])
                if not hits:
                    # a producer whose output isn't on disk yet (never run / template prefix) — note it
                    dangling.add(("(writes) " + name, src_rel, i))
                    continue
                for hit in hits:
                    hit_rel = _rel(hit)
                    producers.setdefault(hit_rel, set()).add(src_rel)
                    writes.setdefault(src_rel, set()).add(hit_rel)

    # Orphans: on-disk assets nobody produces AND nobody consumes.
    orphans = []
    for path in _walk({".png", ".gdshader", ".tres", ".ttf", ".wav", ".ogg", ".svg"},
                      os.path.join(CLIENT, "assets")):
        rel = _rel(path)
        if rel not in producers and rel not in consumers:
            orphans.append(rel)

    return {
        "producers": producers, "consumers": consumers, "loads": loads, "preloads": preloads,
        "loaded_by": loaded_by, "writes": writes, "dangling": dangling, "unresolved": unresolved,
        "orphans": sorted(orphans),
    }


def _fmt_pairs(pairs):
    return ", ".join("`%s` (%s)" % (p, k) for p, k in sorted(pairs))


def render(model):
    L = [BANNER, "# Asset Dependency Map\n",
         "> Generated by `tools/asset_map.py`. `res://` == `client/`. See "
         "[code-map.md](code-map.md) for how to read/regenerate this and the provenance-header convention.\n"]

    # Assets — grouped by directory
    L.append("\n## Assets — producer(s) & consumer(s)\n")
    assets = sorted(set(model["producers"]) | set(model["consumers"]))
    last_dir = None
    for a in assets:
        d = os.path.dirname(a)
        if d != last_dir:
            L.append("\n### `%s/`\n" % d)
            last_dir = d
        prod = sorted(model["producers"].get(a, []))
        cons = model["consumers"].get(a, set())
        prod_s = ", ".join("`%s`" % p for p in prod) if prod else "—"
        cons_s = _fmt_pairs(cons) if cons else "—"
        L.append("- **`%s`** — produced-by: %s · consumed-by: %s" % (os.path.basename(a), prod_s, cons_s))

    # Scripts
    L.append("\n\n## Scripts — loads / preloads / loaded-by\n")
    scripts = sorted(set(model["loads"]) | set(model["preloads"]) |
                     {k for k in model["loaded_by"] if k.endswith(".gd")})
    for s in scripts:
        lo = sorted(model["loads"].get(s, []))
        pr = sorted(model["preloads"].get(s, []))
        lb = model["loaded_by"].get(s, set())
        L.append("- **`%s`**" % s)
        if lo:
            L.append("  - loads: " + ", ".join("`%s`" % os.path.basename(x) for x in lo))
        if pr:
            L.append("  - preloads: " + ", ".join("`%s`" % os.path.basename(x) for x in pr))
        if lb:
            L.append("  - loaded-by: " + _fmt_pairs(lb))

    # Generators
    L.append("\n\n## Generators — writes\n")
    for g in sorted(model["writes"]):
        outs = sorted(model["writes"][g])
        L.append("- **`%s`** → %s" % (g, ", ".join("`%s`" % os.path.basename(x) for x in outs)))

    # Orphans
    L.append("\n\n## Orphans (on-disk asset, no producer & no consumer) — advisory\n")
    L.append("\n".join("- `%s`" % o for o in model["orphans"]) if model["orphans"] else "- none")

    # Dangling
    L.append("\n\n## Dangling references (resolvable ref, file absent) — advisory\n")
    dang = sorted(model["dangling"])
    L.append("\n".join("- `%s` referenced by `%s:%d`" % (p, s, n) for p, s, n in dang) if dang else "- none")

    # Unresolved
    L.append("\n\n## Unresolved dynamic references (path built from a variable — scanner blind spots)\n")
    unr = sorted(set(model["unresolved"]))
    L.append("\n".join("- `%s:%d` — `%s`" % (s, n, raw) for s, n, raw in unr) if unr else "- none")

    return "\n".join(L).rstrip() + "\n"


def generate():
    return render(scan())


def selftest():
    m = scan()
    txt = generate()
    ok = True

    def check(cond, msg):
        nonlocal ok
        if not cond:
            ok = False
            print("FAIL:", msg)

    # V1 — known edges
    crest = "client/assets/ui/crest_v1.png"
    check(any("gen_heraldry.py" in p for p in m["producers"].get(crest, [])),
          "crest_v1.png should be produced by gen_heraldry.py")
    check(any("board_decor.gd" in c for c, _ in m["consumers"].get(crest, set())),
          "crest_v1.png should be consumed by board_decor.gd")
    check(any("board_geometry.gd" in p for p in m["preloads"].get("client/scripts/ui/board_decor.gd", [])),
          "board_decor.gd should preload board_geometry.gd")
    check(any("main.tscn" in c for c, _ in m["loaded_by"].get("client/scripts/main.gd", set())),
          "main.gd should be loaded-by main.tscn (ext_resource)")
    # V3 — templating resolved
    check("client/assets/ui/parch_v1_0.png" in m["producers"] or
          "client/assets/ui/parch_v1_0.png" in m["consumers"],
          "parch_v1_%d.png should expand to parch_v1_0.png")
    # V2 — determinism
    check(txt == generate(), "generation should be deterministic (byte-identical)")
    print("selftest:", "OK" if ok else "FAILED")
    return 0 if ok else 1


def check_mode():
    if not os.path.exists(OUT):
        print("asset-map.md missing — run: python3 tools/asset_map.py", file=sys.stderr)
        return 1
    current = open(OUT, encoding="utf-8").read()
    fresh = generate()
    if current == fresh:
        print("asset-map.md is current.")
        return 0
    print("asset-map.md is STALE — regenerate with: python3 tools/asset_map.py\n", file=sys.stderr)
    diff = difflib.unified_diff(current.splitlines(), fresh.splitlines(),
                                "committed", "fresh", lineterm="")
    sys.stderr.write("\n".join(list(diff)[:40]) + "\n")
    return 1


def main():
    ap = argparse.ArgumentParser(description="Generate the script<->asset dependency map.")
    ap.add_argument("--check", action="store_true", help="exit 1 if the committed map is stale")
    ap.add_argument("--selftest", action="store_true", help="assert known edges + determinism")
    args = ap.parse_args()
    if args.selftest:
        return selftest()
    if args.check:
        return check_mode()
    txt = generate()
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w", encoding="utf-8").write(txt)
    print("wrote", _rel(OUT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
